services:
  frontend:
    build:
      context: ./frontend/ucu-web
      dockerfile: ../Dockerfile
    container_name: frontend
    ports:
      - "80:5173"
    depends_on:
      - app
    volumes:
      - ./frontend/ucu-web:/app
      - node_modules_volume:/app/node_modules
    networks:
      - ucu_network

  app:
    build:
      context: ./backend/src
      dockerfile: ../Dockerfile # Un directorio atrás de "./src".
    container_name: app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./backend/src:/src

    # depends_on:
    #   db:
    #     condition: service_healthy

    networks:
      - ucu_network

  # db service removed for remote DB usage

volumes:
  node_modules_volume:
  # db_data:

networks:
  ucu_network:
