services:
  frontend:
    build:
      context: ./frontend/ucu-web
      dockerfile: ../Dockerfile
    container_name: frontend_votos
    ports:
      - "80:5173"
    depends_on:
      - app
    volumes:
      - ./frontend/ucu-web:/app
      - node_modules_volume:/app/node_modules
    networks:
      - ucu_network

  app:
    build:
      context: ./backend/src
      dockerfile: ../Dockerfile # Un directorio atrás de "./src".
    container_name: backend_votos
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=presi
      - DB_PASSWORD=votosecreto
      - DB_NAME=IC_Grupo3
    volumes:
      - ./backend/src:/src

    depends_on:
      - db

    networks:
      - ucu_network

  db:
    image: mysql:8.0
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: IC_Grupo3
      MYSQL_USER: presi
      MYSQL_PASSWORD: votosecreto
    ports:
      - "3306:3306"

    volumes:
      - db_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
      
    networks:
      - ucu_network

volumes:
  node_modules_volume:
  db_data:

networks:
  ucu_network:
