services:
  db:
    image: mysql:8.0
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: IC_Grupo3
      MYSQL_USER: presi
      MYSQL_PASSWORD: votosecreto
    ports:
      - "3306:3306"

    volumes:
      - db_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
      
    networks:
      - ucu_network

volumes:
  db_data:

networks:
  ucu_network:

